[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbfdfb4864066a677dcebba0207aeb492579d48f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "9e4f2e935866fbad5f31c47aae5e6c6424b27af31c5bc83160e879774a5a8a4c"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb5aba6d13af69aa69c959f74b5915d1c6bab0b2"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "359471332fd7fe43710285bccfefff74caf060840f8cf7bd218de1c6759c326d"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e033c194ad66332c1ae5410ecb161c679e3400f"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "156ae4621870425b113b40bc68d0d10a4fba15eba12495e4ac60b54af99e9bd5"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6015dc37215ffa98c5a8220751bcb28593019e75"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "3dc64c781e786853ae02bff9b5c0cd2582e9d908fb4fcf18900a4de61a7a9a5c"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca2cd8afb27c2dc4ebb1ab8f69e740f2dc13cbf4"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "8eed44c3349affeb289622aeef7b96f01512891656f58d8c2f4c87d97b323ea1"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f72038016adf9fc5224dd6f9bf38e6a0a92ad1ac"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "937e2f5fd1e8a512353099e70fa2dab445b089a7f5cd2da3a2828fd366ab2c17"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b75b612a6156f0352ff96e105efd18b1d36cfbf"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "389d39f8f90a4cc9dc809c3fab5670eb6ed05ac95b6dc7b692b9934021f9ec49"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49f7564ea51d61878f82d9644befc53a88aaa8c6"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "5a01982fa5059d34b6e0b39e8a89b5ff2d1b37790aeb52c24ed7b392d5c4e934"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cd119099d9838a47baa70c8d6b29874eeb8794c"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "f00966814e92cb2547eb0144b39bdc1e631d85fb5464ed1748798202eb3f6749"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78a72ca5438862d6f5efc09196c683192e25cf8c"
julia_version = "1.10.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "2ea6ffe68e06a5c8d6d520cf2eef202363251d7a7318f1851017db7b4e852872"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41b13373f52533f7bacac8fedd28e5c62cbb6982"
julia_version = "1.11.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "3c8695eaac26e4796905a2d2853b8dbb6504d56c3ba86f541bb1b6c3b9bc1970"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "654bdb487b64f5549918ec702e21529df9956f56"
julia_version = "1.12.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "8c1c00c30d6357dde143f8d411bcec8ca5c4804c6836f125b49b3e0071c409f7"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.5+1/voropp_wrapper.v0.1.5.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
