[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc4e8db10ca7929d560f62712ab474e7fc069066"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "038bd3f9b35020f6760d8876ffc5dad7b6f3c14cbbe03dbda761735421cbbba3"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75a64c717713db9b752394836adf31295a364bf8"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "4173d227110037327083de9bc8b604fe17c47e1e6ecd6ee0ceba57da7e660da3"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "087a8675a69dad0f7d1de1879e4b16421c1f41ee"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "e56fe778c541dd6ab8b0a1d488f532b757a76954532aa772a03d81d86466881a"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "439267e2c482d2dafd9c00c9d556f3ebb86daf03"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "b50981087713dca887d52faff463e4aaa397048a55d7264eb175d8ba2da9002c"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6ccc16783b3f5d134f2d4bf993e64298922cc81"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "b0497a144f5588a58be6557d00d1bc7e956692d371f666c3ee989a1c15f4a724"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "853004fda79d4a73c31e4746c97a5b10fa40d4a8"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "ee70908ef966e9d9306caddae50a458adb1b2cd9f0f27e765e337cee6d6f57f3"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93fce287a73e2fc01a1079812d5a4a0798110d7f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "b8f54e54acf7d1eefc974a3d15bb2a5774ce149b61421e8e0c59b7961b02a5cb"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d34c9e407b584d111e5fa843e2a5835d5516da77"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "84ed4b66530d3d03a0b5f58b57f2ca94e96809325ebe2b5eede16cb20edbd284"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efd7e70a090696d30012f18e42b5c56189589391"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "5180450ea9f73feb799bf011b7308888343ad1b263730e894eec17836c128f1a"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edfc3ba7dbd0069bb7be3e8898ccf202b1b11f6d"
julia_version = "1.10.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "ff1d5c5d767e569fb63d875e0cd7ba4dbb4828c7f9680ec9b6c6481ef5316891"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee865826978f2903f25334d1f06c19cdbc75e109"
julia_version = "1.11.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "726d9b9cc5ddde852da8c70e2e237d3ce2384807368005244a2d5fea725ad34f"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26c8c8b896c82caaf26e8b03f7c24ccfd7d436e7"
julia_version = "1.12.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "8eb7fc117bf10598a1a791010e0b8866025dd4330cc5d11212baabaf86eb9e44"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.2.0+0/voropp_wrapper.v0.2.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
