[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc16fd7998249a70232bce76647280fdbaa7b537"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "ee295e7c73d2bdac54da3f942aa739e8eff6aac212eca183f6b6aba3fdbce733"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92c20586ef0db751ec0227ac48777cf823c433f4"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "af032478e612cc3ba4acbd844a8a20117fcfab7552a2b5cfa7766404ab8445c1"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78057138091359942d023d722839f161ef685416"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "70ad77d966a6d848405bd214050c5c4be87901c29a302e2827c51db72a5861d3"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1911afdd3edc7d933f22a1b20274436f04967878"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "2cac33e6d8c60fb2595e7aa4ecc3907966cf5360354e91a1f21e55c7e91aef4d"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "508df4a767b907a549c6db2843bd0cb96a5c6f3c"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "75046a3558062c3159e56f98794397f5f9153d14f392e090e8e75f173faa8592"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "664059145f4da23a0c6427d0234cf508b984e5b4"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "1b42f922e6a1c5b097b94f6f24b20c4b617d19f42bad3374e27309cfb82d0691"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "981855ca546313f11584300f2ac4301f68d96733"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "c67e29c4651ac50819ae769d3e708a470b9ee9560fb6aef69656bb599783bebd"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "969ddf9f6eaebb4528b07efcd9bd6bc29216fb49"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "ed09d40dc089b5ebcc0d2d8a9b94a9cbb268996b29962e9ffe5e832729aef284"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cc6b933fe67ce8d47ea6c21472626c93a596977"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "3e8cc5b94e7389b1cacb6a0b032978cfa137a787113afb070a3418f2d222bdf8"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408c595795c01df90b066a8d23ce5e837799f743"
julia_version = "1.10.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "a628a5faeba3db07c1a5f910f20bcc19181092056e4b4bbcdc6802e43ad356fc"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "067cdafe1ec03a4420731c769bbddbc701efb6fa"
julia_version = "1.11.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "9efd308ced4ddd02b13489d623c144397d6b5661629bb7310528bbe963112f85"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ffbdd3e7ed4072abad033c77cfdc4db27f07ff"
julia_version = "1.12.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "78c4a41bd2e802c6eb1f2cf47d0198f5a07eba94160857c20feacbb7221f8773"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.3.0+0/voropp_wrapper.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
